### ISSUE TITLE
[Client thread/WARN] [HarvestTweaks-Blocks]

### ISSUE THREAD

**Issue by bookerthegeek** [SlimeKnights/HarvestTweaks#12]
https://gist.github.com/bookerthegeek/22a6e0a178cf961b7060d56451a0d9d4

Seem a lot of blocks are not supported. Just letting you know in case this is important to you.

**Comment by bonii-xx** [comment]
Sadly it's the other way around: Those blocks do not support their harvest level being changed. HarvestTweaks only uses the Forge provided API to change harvestlevels.. and those blocks are either doing it wrong or are more complex in their harvest behaviour that they can't support it statically. There's nothing to do on my side.
