### ISSUE TITLE
Broken Tinkers tools completely ignore harvest levels

### ISSUE THREAD

**Issue by WesCook** [SlimeKnights/HarvestTweaks#13]
This is a rather major bug [as reported to me here](https://github.com/WesCook/Homestead/issues/26).

Steps to reproduce:

1. Install Tinkers, Mantle, and HarvestTweaks
2. Create a world and spawn in two Tinkers wooden pickaxes.
3. Break one pickaxe quickly by mowing down some tall grass.
4. Place two diamond ore blocks on the ground.  Try mining one with a full pick, and one with a broken pick.
5. The full pick respects harvest levels, while the broken pick does not.

This only occurs if HarvestTweaks is installed.  Tinkers alone will not cause this.

**Comment by bonii-xx** [comment]
Mods and Minecraft versions?

**Comment by WesCook** [comment]
Mods are just the three mentioned above: Tinkers, Mantle, and HarvestTweaks.  The latest version of each with freshly generated configs.

Minecraft 1.10.2
Forge 12.18.3.2316.

Normally I wouldn't report bugs for older versions of the game, but it's the latest (and only) version that HarvestTweaks supports.  This is also a rather critical bug, so I thought it best to address.

**Comment by bonii-xx** [comment]
Hm, I can't reproduce this in my dev environment.
Using a wooden tinkers' pickaxe and a cobalt ore and diamond ore.

**Comment by WesCook** [comment]
Hrmm, could the dev environment be interfering?  I just set up a fresh environment.  Redownloaded the three mods above and could replicate the bug.

I recorded a short video to show this happening.

https://www.youtube.com/watch?v=dPVIP5YkMSw

And here's how the mods folder looks:

![2017-09-09 14_39_01-mods](https://user-images.githubusercontent.com/792101/30244266-d7ac36e8-956f-11e7-867f-a65473f51d02.png)

**Comment by bonii-xx** [comment]
My bad, I had the wrong TiC version. Turns out 2.5.6 is not 2.6.5. I can reproduce it now.. but that also means it game with a change in TiC.

**Comment by bonii-xx** [comment]
Found the cause. Thanks for the report. New version will probably be soon.

**Comment by WesCook** [comment]
Wonderful, thank you!
