### ISSUE TITLE
[Request] Additional Harvest Levels

### ISSUE THREAD

**Issue by NielsPilgaard** [SlimeKnights/HarvestTweaks#15]
Hey!

Would you consider adding the ability to add/remove harvest levels?
I'd like to have additional levels between Stone and Diamond, and some after Manyullun.

**Comment by bonii-xx** [comment]
You already can do that. You just have to adjust the harvestlevel of everything in between.

**Comment by NielsPilgaard** [comment]
Ah okay, thanks. What about editing the name of levels?

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/Overwriting-Harvest-Levels

**Comment by NielsPilgaard** [comment]
Thank you very much.

**Comment by bonii-xx** [comment]
You're welcome, those things were built with that in mind. It uses resource packs so it's possible in multiple languages too. It's just not very common, so it's not put out there much.

**Comment by NielsPilgaard** [comment]
Can you tell me how to apply it by default, so people who download the modpack don't have to set it themselves?

**Comment by bonii-xx** [comment]
Try https://minecraft.curseforge.com/projects/resource-loader
I think that should work

**Comment by NillerMedDild** [comment]
I can't seem to get it to work, would you mind having a look at it?

https://drive.google.com/open?id=0Bx0PHXshCZFqRHJDaVM1SndwN0E

That's the resource pack.

**Comment by NielsPilgaard** [comment]
I can't seem to get the resource pack to work at all, would you mind taking a look?
It shows up in the resource pack selection menu, but it doesn't actually change anything.

https://drive.google.com/open?id=0Bx0PHXshCZFqRHJDaVM1SndwN0E

**Comment by bonii-xx** [comment]
What version? needs to be all lowercase in 1.11+

**Comment by NillerMedDild** [comment]
Ah! It's 1.12.1

**Comment by NielsPilgaard** [comment]
Ah, it's 1.12.1
It already is lowercase though.

**Comment by NielsPilgaard** [comment]
Do you have a functional example resource pack that changes TiC harvest levels, by chance?

**Comment by bonii-xx** [comment]
No, your file is named en_US.lang, it needs to be en_us.lang though. Lowercase.

**Comment by NillerMedDild** [comment]
Oh, I thought you meant the contents of the file ^^'

**Comment by NielsPilgaard** [comment]
And it works!
Now I just need to get it to work with Resource Loader. 

I really appreciate the help :)

**Comment by bonii-xx** [comment]
Tell me if it works with Resource Loader, or if that requires special integration.

**Comment by NielsPilgaard** [comment]
I haven't been able to get it to work, and I can't any useful information about it either.

I'm going to include the options.txt to auto-select the resource pack, but it's not a great solution.
