### ISSUE TITLE
[1.12.1] Unable to change Tinkers tools

### ISSUE THREAD

**Issue by NielsPilgaard** [SlimeKnights/HarvestTweaks#16]
Heya!

I'm unable to set harvest levels of all Vanilla-TiC pickaxes to above harvest level 4. It works for about 25% of  PlusTiC pickaxes.
I have succesfully changed the harvest levels of some ores beyond level 4.

[Configs](https://drive.google.com/open?id=0Bx0PHXshCZFqX1ZrLVRCR0lldkk)

**Comment by Thyriel** [comment]
I have a smiliar issue: (not using PlusTic at all) Changing the harvest level of any TC material doesn't work at all. For example i changed the values in the generated TinkerConstruct.cfg if iron to 1, flint and stone to 0 and some more. None changed anything so far.

I even tried _log_changes"=true to see if i can find anything in the log file, but either i'm too dumb to find it or there's just nothing in the logfile at all. (changing harvest level of ores and blocks works fine btw)

@NillerMedDild: Are you sure it's working at all for any vanilla-Tic material to change harvest level as it's not working for me (and not only >4 isn't working) ?

edit:
fml-client-latest:: https://pastebin.com/sKDPNsNr
HarvestTweaks/TinkersConstruct.cfg: https://pastebin.com/nqVWEaSZ

**Comment by NielsPilgaard** [comment]
It's entirely possible it's not changing any TiC tools, and the PlusTiC tools just have weird default levels, ranging from 6-14.

**Comment by Thyriel** [comment]
@bonii-xx any idea on this ?

**Comment by bonii-xx** [comment]
Sounds like some hook broke in the update, needs debugging.

**Comment by Thyriel** [comment]
k, in the meanwhile just if it helps someone too bypassing that problem: The mod "Tool Progression" can tweak Tinker tools mining level in 1.12
