### ISSUE TITLE
Setting a block to require tool to prevent drops instead of preventing breakage?

### ISSUE THREAD

**Issue by Vampsku11** [SlimeKnights/HarvestTweaks#21]
Is it possible to prevent blocks from dropping resources instead of preventing blocks from being mined at all without the proper tool? For example, clay would only drop clay when mined with any shovel, logs and planks would only drop themselves if mined with any axe. Similar to how stone behaves, it will only drop cobblestone when mined with any pickaxe.

**Comment by bonii-xx** [comment]
No. This is defined deep in Minecraft in a non-changeable way. It'd require specific workarounds for minecrafts behaviour.
