### ISSUE TITLE
Tool progression

### ISSUE THREAD

**Issue by mainrs** [SlimeKnights/HarvestTweaks#23]
Is it possible (similar to iguana tweaks) to make certain materials change their harvest level over time? Not sure if this mod allows it or not. It would probably make sense to embed it with the tool leveling approach one of your other mods adds to TiC. 
If this is not possible, would a custom mod be able to achieve this? Maybe in the logic of ' if this pick harvested 400 blocks, change its harvest level to the next one?' or is this not possible after registering all materials for the tools?

**Comment by bonii-xx** [comment]
It is possible, in theory, but this mod only allows for changing the harvest levels of blocks/tools/materials.

**Comment by mainrs** [comment]
Thank you for the answer!
