### ISSUE TITLE
Is there a way to change names of TC mining levels?

### ISSUE THREAD

**Issue by rhoark** [SlimeKnights/HarvestTweaks#24]
In my pack I'm being careful with what requires or allows mining levels above diamond. Cobalt and Manyullyn materials are set to levels 2 and 3; however, the names of levels 4 and 5 are still called cobalt and manyullyn. Is there a way to change these level names?

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/Overwriting-Harvest-Levels
