### ISSUE TITLE
1.10.2 - Names of "Mining Levels"

### ISSUE THREAD

**Issue by MrLador** [SlimeKnights/HarvestTweaks#26]
Hello, I didn't find a way to change the names of "Mining Levels" in Harvest Tweaks fashion. Write in what file this can be done. For example: "Ardite"= 6 Levels - how will it be in the code (+text color)?
Harvest Tweaks: 0.1.3
Minecraft: 1.10.2
Forge: 12.18.3.2511

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/Overwriting-Harvest-Levels
