### ISSUE TITLE
1.12.2 Dangerous alternative prefix

### ISSUE THREAD

**Issue by Maxwelljones** [SlimeKnights/HarvestTweaks#31]
Hello,

Reporting this issue to trigger warnings/errors during loading
It is safe to ignore the warning as stated here --> in another mod: https://github.com/brandon3055/Draconic-Evolution/issues/926
But it would be great to prevent those messages from showing.

forge: 14.23.5.2768
Mc 1.12.2
Logs: https://pastebin.com/Uty6e64N

**Comment by SweetSugarSugar** [comment]
Yes, it's fine and it's intended...

Try searching your issue first next time.

Duplicate of #2219, #3230, and #3268

**Comment by bonii-xx** [comment]
Those are TiC issues though. The problem also is in TiC. But don't worry, everything is fine.

**Comment by Maxwelljones** [comment]
Thank you .. and sorry for not searching properly.
