### ISSUE TITLE
crash on breaking block

### ISSUE THREAD

**Issue by TheNimbleNinja** [SlimeKnights/HarvestTweaks#32]
https://gist.github.com/TheNimbleNinja/cc4686047576a69a9aa4642c6aceb1d2

**Comment by KnightMiner** [comment]
Update the mod, this is fixed in the latest release on CurseForge.

**Comment by TheNimbleNinja** [comment]
are you talking about alpha 1.6

**Comment by KnightMiner** [comment]
Yes. Not sure why its still marked alpha, but that latest release in the changelog says it fixes this bug.
