### ISSUE TITLE
Crash after adding HarvestTweaks to a modpack

### ISSUE THREAD

**Issue by belathus** [SlimeKnights/HarvestTweaks#4]
http://pastebin.com/raw/TBP1BnyZ

I updated Mantle after first getting this crash, but it didn't seem to help (this report should be after the updated Mantle).

**Comment by bonii-xx** [comment]
PrimalCore and/or whatever is using it is at fault. They're throwing errors they probably shouldn't throw. You'll have to talk to its dev.

**Comment by belathus** [comment]
Will do!

**Comment by An-Sar** [comment]
I am looking into this on my end. Thank you for the report.

**Comment by bonii-xx** [comment]
Error is a really weird thing to throw, some Exception would be more appropriate. (Exception scenarios also are handled on my side. Errors are meant to not be handled)

**Comment by An-Sar** [comment]
I don't even really need to throw an exception in this case, it was some old code left over from debugging. I added HarvestTweaks to my dev environment and it's working now so we should be good.

**Comment by belathus** [comment]
This is resolved.
