### ISSUE TITLE
Harvest level config file

### ISSUE THREAD

**Issue by DarkCorvuz** [SlimeKnights/HarvestTweaks#7]
Hiya,

a suggestion or rather a friendly request if you have time and feel like obliging a starting modpackdev.

Can you add a harvest level config file that can display in the materials and you books the harvest levels?
I'm making a modpack with heavy emphasis on a different kind of mining using WTF expedition for a different kind of oregen and i would like to use harvest tweaks to make things even more challenging and more forced progression like, i will even include tweaked recipes and a HQM to make it a hardcore expert mode like thingy.
For that reason i would like 12-ish different harvest levels, so what i would like is a simple config file where i would be able to specify:

harvest level 0 = iron 
harvest level 1 = copper
harvest level 2 = lead 
...
harvest level 10 = yellorium
and so on 

and when the players look in the tinkers handbook the mining levels are displayed accurately.

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/wiki/Overwriting-Harvest-Levels

**Comment by DarkCorvuz** [comment]
ok i'm sorry for bothering you with this but how do i go about creating a localization file via resource packs?
i'm a total noob at this and my google skills fail me

is this the way?
create a folder assets/tconstruct/lang/ in a resource pack
and place a file called en_US.lang into there

**Comment by bonii-xx** [comment]
You are correct, instead of having a textures/models folder you have a lang folder with the localization in there. You could also try the [Resource Loader](https://minecraft.curseforge.com/projects/resource-loader) mod, but I have no idea if that works for this case.

**Comment by DarkCorvuz** [comment]
Thank you so much ...
this is cool i'm learning new stuff as i go :) it takes me a while to figure it all out though
I will definitely check resource loader, thank you for the tip
